// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateRedirect(ctx context.Context, arg CreateRedirectParams) (Redirect, error)
	DeleteRedirect(ctx context.Context, id int64) (Redirect, error)
	GetRedirect(ctx context.Context, id int64) (Redirect, error)
	GetRedirectByActiveLink(ctx context.Context, activeLink string) (string, error)
	GetRedirectByHistoryLink(ctx context.Context, historyLink string) (string, error)
	ListRedirects(ctx context.Context, arg ListRedirectsParams) ([]Redirect, error)
	UpdateRedirect(ctx context.Context, arg UpdateRedirectParams) (Redirect, error)
}

var _ Querier = (*Queries)(nil)
